name: Azure Container Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.Azure_register_password}}

    # - name: creation d'un registre de container
    #  run: |
    #   az acr create --resource-group ChaubarouxMel --name b15ajaxmc --sku Basic --admin-user-enabled true

    # - name: recuperation du mot de passe
    #  run: |


    #   az acr credential show --name b15ajaxmc

    - name: run test
      run: |
      pytest test


    - name: Build and push Docker image
      run: |
        cd ./back
        docker tag ajax_back b15ajaxmc.azurecr.io/back
        docker push b15ajaxmc.azurecr.io/back

        cd ../front
        docker tag ajax_front b15ajaxmc.azurecr.io/front
        docker push b15ajaxmc.azurecr.io/front
      
    - name: Deploy to Azure Container Instances front 
      run: |
        az container create \
         --resource-group ChaubarouxMel \
         --name mel-ajax-front \
         --image b15ajaxmc.azurecr.io/front \
         --dns-name-label mel-ajax-front \
         --ports 7000 \
         --registry-username ${{Azure.register.user}} \
         --registry-password ${{Azure.register.password}}

    - name: Deploy to Azure Container Instances back
      run: |
        az container create \
         --resource-group ChaubarouxMel \
         --name mel-ajax-back \
         --image b15ajaxmc.azurecr.io/back \
         --dns-name-label mel-ajax-back \
         --ports 8000 \
         --registry-username ${{Azure_register_user}} \
         --registry-password ${{Azure_register_password}}
    
    
        